### ISSUE TITLE
Cleanup DNS

### ISSUE THREAD

**Issue by timwhite** [plugorgau/admin#3]
Lots of old servers still in DNS. Probably should make sure DNS is in Git as well

**Comment by timwhite** [comment]
Some cleanup has now been done. I've not yet updated the serial or pulled it so people can review it
See https://github.com/plugorgau/dns/compare/ceeca7...master for a diff

**Comment by HybridAU** [comment]
That looks good.

After looking at the [zone file](https://github.com/plugorgau/dns/blob/32234c0b81d6bf2ac704ee3a540b5420d4b54e10/plug.org.au.zone) I realized I missed out secure.plug.org.au from the SSL Certificate when I was setting up Let's Encrypt. I'm not sure if we use it any more, but I'd be tempted to remove secure and change Apache to redirect all HTTP requests and make the whole site HTTPS only.

I also missed rt, ns1 and icecast from the cert. I can renew our cert manualy to add them before we change to HTTPS only.

**Comment by timwhite** [comment]
IIRC, with lets encrypt you can easily add more domains to the same cert, and just run a renewal. That way they are just added as subject names to the existing cert.

**Comment by timwhite** [comment]
Updated DNS on power. Fixed up delegation to secondaries (they have new hostnames going forward, old ones will eventually be retired). Pinged LA to update NS delegation for plug.linux.org.au.
