### ISSUE TITLE
Setup password vault

### ISSUE THREAD

**Issue by timwhite** [plugorgau/admin#4]
It's hard to know what the current passwords are for things like Mailman. Once upon a time, they lived in a GPG text file that we all had to update our own copy of.
Now days, we have things like https://github.com/timwhite/TeamPasswordSafe that allow us to keep them in a secure central location.

If no one objects, I'll setup an instance on power so we can centralise passwords

**Comment by HybridAU** [comment]
I don't have an issue with setting up a password safe, although we do have a LastPass account and I think we should pick one thing and make sure we stick everything into it or find some way of keeping them in sync.

Personally I like self hosted things but they are more maintenance so there is always a trade off.

Is [this](http://pgp.mit.edu/pks/lookup?search=0x20A76ABD&op=vindex) your PGP key? I can send you a PGP email with the password to the LastPass account if you don't have it.

**Comment by timwhite** [comment]
My personal key is http://pgp.mit.edu/pks/lookup?search=0x5165B1F4

I wasn't aware of the Lastpass. Do we still have a wiki anywhere? Might be good to start one if we don't, too much kept in peoples heads.
I wrote TeampasswordSafe because I don't like LastPass having the keys to the kingdom, or the cost. Happy to stick with LastPass

**Comment by HybridAU** [comment]
```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMA0ayTXR30DTyAQ//UoeATLl8in02p3ai6f81kRsxY1b1QEZy3ATnluPWpqPg
cQwCv3kaD4iZJZGt85Xazpvs/7Oj0mRbAVHjAjHus788xX158fYYZAL+mGto8zA0
0avjd/7fxnGRzxEdysJPDnpDQti0svUGu3EiRRbuP8nE30K7JZq+gjEaP5w9FDZi
viBMmjED1BQLk/Qgy7WfAaH0830yX0ZTZKt+cfvvRoWMg203yF/Gl6sk8wQgtCK3
LKtXL/pcASQf56NUsyJm4RtxyzblVWuiIzcdVpjimEFRymzhv07fWU25z2s72sua
FESgZl0VM4mUw05Atxev4buUxiU/vFMoIMAWvpARC6FI6REmSuwkqchGSWfHuE8y
95c4GzkVffl8GAKbWbM35uSvsdwv40Cr/FAUWhRT1h19nprzxPYoPlSUp+Sqzibn
fK8BWRobZa4UTCTa4/vf4DFmu85S8SIHMnfc0/N+wTJ4MMBljXpIXSjGv5Jpzeum
g7WhQkaS+/gPqpZJiyR0zHxfauXClB0Xk8NSZj5SrOftPSrHbm0zOdHZk2vRY6cc
9r0dBxQX6I5psv7Mk/Bjnhac6qZd5r9MzApbc2iEzCADSFQDWlpvNz8VeYs4ZkEQ
gOFYqyhBW8H0fG9Oy1zrYpqV7y43IKgcDWFMMn11+OnmaLROmJBNneDL3sBuiCPS
6QEh4HV1AdK6Sxfk0v1FISjOz4kGau2DKxsKv1Q4g02a4pYwSPIDtPPN4Y7lZ6dy
jx6iRlZuLaR5VxWl6Be1vfPwz1L5Fywkf5U7fUVZ4Mz2biG4Tle+Kbxtfxzgx0v+
3ovYdY+CR1AS/EiS029da8zer0UDDUTSBG4Xvmz55M9hx9SGyA2Nr6x3KxO4eDXX
0w3WxfEmg/kj5gGowfmcOnaRHnidi/Z0P5uCUd/vzzYaRCbjLl7HlO/R8u+NDib9
fKrZy9w4enaXjsc3AXKdCFAJNGIJXkhxqNB2sFPROJg2281stsZoT8tfu+L0/iLD
5tb7OfHt9UUql8S/EVj1N4ARyxAuoT9H1T2hUHCs24CSXrcxLeZxkhAqHPXkM5db
1T781EWIlcvAgoVp9XWuTi/JEnu64EwmIeBOqfmCNasyYVdkU9N32Py3Gw8mUXu3
1GjvBTkCwYQ6tfTU/SklNgIasXe7SqfwcZf7fo2JbEgvBjtD27CGMGu1O8MZRUKS
3U/fon/QL0YPvba71kyQhlHIYbehnU7tvLWhRTPiPI04m8UxFeNyKAxz+QXcXOHk
aweLEohq1c0EGcTql5JmZ++EfgnEedQEOGrrJlD+f1rGpbdQYChB986EguNvOXT2
umwEhI+SmaSwcmgtBrF85CIGDGLB9895lEPmpD7rtkVWwDbjzpvjLDmSPKyu6HPQ
Wk8wqkIqufA3TXLyNdbN9s+8sOqYK6xOmdYvEGejhsxxCmTIk+3gcU26Cod9eB89
urMtuCl2eGLE3jpp5x3EwbhFC3GNjT+oSzWdv9s1LEKJNe8gZzCDp/7qOXwEX7I1
AEDBCLm5tHkuxTyz4Y0HZLjG7RYiqsG7P8Gvb8h7Smg9U6qPLl82/tNb7/0ewDQa
OVcK8b99LXkiJLyQ6qzLTP+39ncCZEyPjw9tFjZdwGLHbFpFiFuuggghM+s9/Tss
GLiwDPffSLt/+0ivGbFUoLx8g5b/ASS82hGdViTunOBvhIyLVMbkbcw=
=CoBp
-----END PGP MESSAGE-----
```

I don't think there is a wiki, we have a shared document in Google Docs that has a bit of information about the servers. Do you have a Google account I can share it with?

**Comment by timwhite** [comment]
timwhite88 Gmail.
Thanks
